version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "pandas"
      - dependency-name: "numpy"
      - dependency-name: "sqlalchemy"
