database:
  url: "sqlite:///financial_data.db"
  test_prefix: "test_"

processing:
  # If true, skipped transactions will be shown again for reprocessing
  # If false, skipped transactions will be automatically skipped (like processed transactions)
  reprocess_skipped_transactions: false

processors:
  icici_bank:
    extractor: "icici_bank_extractor"
    transformer: "icici_bank_transformer"
    file_type: "excel"
    extraction_folder: "data/icici_bank"
    currency: "INR"  # Single currency

  # Example multi-currency processor:
  # icici_forex:
  #   extractor: "icici_forex_extractor"
  #   transformer: "icici_forex_transformer"
  #   file_type: "excel"
  #   extraction_folder: "data/icici_forex"
  #   currency: ["USD", "EUR", "GBP", "INR"]  # Multiple currencies

enums:
  # Example enum structure - will be populated interactively
  # salary_company:
  #   patterns: ["company", "salary"]
  #   category: "income"

# Categories are now loaded from config/categories.yaml
# Copy config/categories.yaml.example to config/categories.yaml to customize your categories
