database:
  url: "sqlite:///financial_data.db"
  test_prefix: "test_"

processing:
  # If true, skipped transactions will be shown again for reprocessing
  # If false, skipped transactions will be automatically skipped (like processed transactions)
  reprocess_skipped_transactions: false

# ML-powered contextual transaction categorization
ml:
  enabled: true
  confidence_threshold: 0.75
  max_suggestions: 5  # Maximum number of suggestions to show per category. Set to 0 to disable suggestions, 10+ may overwhelm users
  feature_extraction:
    min_pattern_length: 3
    max_pattern_length: 50
    min_description_length: 5
  similarity:
    fuzzy_threshold: 0.8
    cosine_threshold: 0.7
  learning:
    feedback_weight: 1.5
    decay_factor: 0.95
    short_term_days: 30
  models:
    naive_bayes_alpha: 1.0
    tfidf:
      max_features: 1000
      min_df: 2
      max_df: 0.8
      ngram_range: [1, 2]

processors:
  icici_bank:
    extractor: "icici_bank_extractor"
    transformer: "icici_bank_transformer"
    file_type: "excel"
    extraction_folder: "data/icici_bank"
    currency: "INR"  # Single currency

  # Example multi-currency processor:
  # icici_forex:
  #   extractor: "icici_forex_extractor"
  #   transformer: "icici_forex_transformer"
  #   file_type: "excel"
  #   extraction_folder: "data/icici_forex"
  #   currency: ["USD", "EUR", "GBP", "INR"]  # Multiple currencies

enums:
  # Example enum structure - will be populated interactively
  # salary_company:
  #   patterns: ["company", "salary"]
  #   category: "income"

# Categories are now loaded from config/categories.yaml
# Copy config/categories.yaml.example to config/categories.yaml to customize your categories
