name: Commit Message Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Validate Commit Messages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install commitlint
      run: |
        npm install -g @commitlint/cli @commitlint/config-conventional

    - name: Validate commit messages
      run: |
        commitlint --from HEAD~10 --to HEAD --verbose
