name: Code Formatting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: "3.9"

permissions:
  contents: read
  actions: read

jobs:
  format:
    runs-on: ubuntu-latest
    name: Code Formatting

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt

    - name: Run Black formatter
      run: |
        black --check --diff --line-length=100 src/ tests/ scripts/ config/

    - name: Run isort
      run: |
        isort --check-only --diff --profile=black --line-length=100 src/ tests/ scripts/ config/

    - name: Check for trailing whitespace
      run: |
        find . -name "*.py" -o -name "*.yml" -o -name "*.yaml" -o -name "*.md" -o -name "*.txt" | xargs grep -l " $" || echo "No trailing whitespace found"
